# 0D Tensors / Scalar 

In [1]:
import numpy as np

In [4]:
a = np.array(8)
a
type(a)

numpy.ndarray

In [5]:
a.ndim

0

# 1D Tensor / Vector

In [ ]:
arr = np.array([1,2,3,4])
arr       # 1d tensor 


array([1, 2, 3, 4])

In [10]:
arr.ndim

1

In [ ]:
import numpy as np 
tensor_1 = np.arange(1,11)
print("1D Tensor: " , tensor_1)
print("Sum: " , np.sum(tensor_1) )
print("Multiplied: " , (tensor_1 * 2))


1D Tensor:  [ 1  2  3  4  5  6  7  8  9 10]
Sum:  55
Multiplied:  [ 2  4  6  8 10 12 14 16 18 20]


# 2D Tensor 

In [12]:
array1 = np.array([[1,2,3] , [3,4,5] , [6,7,8]])
array1

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
array1.ndim

2

In [22]:
import numpy as np 
tensor_2 = np.arange(1,10).reshape(3,3)
print("Tensor 2D: " , tensor_2)
print("sum of each row: " , np.sum(tensor_2 , axis=1))
print("sum of each coulmn: " , np.sum(tensor_2 , axis=0))
print("Multiplied by 3:\n", tensor_2 * 3)

Tensor 2D:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of each row:  [ 6 15 24]
sum of each coulmn:  [12 15 18]
Multiplied by 3:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]


# 3D Tensors

In [23]:
tensor_3d = np.arange(1, 25).reshape(2, 3, 4)  # 2x3x4 tensor
print("3D Tensor:\n", tensor_3d)
print("Sum along last axis (columns):\n", np.sum(tensor_3d, axis=2))
print("Maximum value:", np.max(tensor_3d))
print("\n")

3D Tensor:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Sum along last axis (columns):
 [[10 26 42]
 [58 74 90]]
Maximum value: 24


